// Mocks generated by Mockito 5.4.6 from annotations
// in ate_app/test/mocks/mock_services.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i10;

import 'package:ate_app/models/dish.dart' as _i19;
import 'package:ate_app/models/notification.dart' as _i12;
import 'package:ate_app/models/post.dart' as _i15;
import 'package:ate_app/models/restaurant.dart' as _i18;
import 'package:ate_app/models/review.dart' as _i21;
import 'package:ate_app/models/user.dart' as _i6;
import 'package:ate_app/repositories/auth_repository.dart' as _i13;
import 'package:ate_app/repositories/follow_repository.dart' as _i22;
import 'package:ate_app/repositories/post_repository.dart' as _i14;
import 'package:ate_app/repositories/restaurant_repository.dart' as _i17;
import 'package:ate_app/repositories/review_repository.dart' as _i20;
import 'package:ate_app/repositories/user_repository.dart' as _i16;
import 'package:ate_app/services/backend_service.dart' as _i5;
import 'package:ate_app/services/firebase_auth_service.dart' as _i7;
import 'package:ate_app/services/firestore_service.dart' as _i8;
import 'package:ate_app/services/notification_service.dart' as _i11;
import 'package:cloud_firestore/cloud_firestore.dart' as _i3;
import 'package:firebase_auth/firebase_auth.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserCredential_0 extends _i1.SmartFake
    implements _i2.UserCredential {
  _FakeUserCredential_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseFirestore_1 extends _i1.SmartFake
    implements _i3.FirebaseFirestore {
  _FakeFirebaseFirestore_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCollectionReference_2<T extends Object?> extends _i1.SmartFake
    implements _i3.CollectionReference<T> {
  _FakeCollectionReference_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFieldValue_3 extends _i1.SmartFake implements _i3.FieldValue {
  _FakeFieldValue_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWriteBatch_4 extends _i1.SmartFake implements _i3.WriteBatch {
  _FakeWriteBatch_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_5<T1> extends _i1.SmartFake implements _i4.Future<T1> {
  _FakeFuture_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeImageUploadResult_6 extends _i1.SmartFake
    implements _i5.ImageUploadResult {
  _FakeImageUploadResult_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMultiImageUploadResult_7 extends _i1.SmartFake
    implements _i5.MultiImageUploadResult {
  _FakeMultiImageUploadResult_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeModerationResult_8 extends _i1.SmartFake
    implements _i5.ModerationResult {
  _FakeModerationResult_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeValidationResult_9 extends _i1.SmartFake
    implements _i5.ValidationResult {
  _FakeValidationResult_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUser_10 extends _i1.SmartFake implements _i6.User {
  _FakeUser_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FirebaseAuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseAuthService extends _i1.Mock
    implements _i7.FirebaseAuthService {
  MockFirebaseAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i2.User?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i4.Stream<_i2.User?>.empty(),
          )
          as _i4.Stream<_i2.User?>);

  @override
  _i4.Future<_i2.UserCredential> signUp({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i4.Future<_i2.UserCredential>.value(
              _FakeUserCredential_0(
                this,
                Invocation.method(#signUp, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.UserCredential>);

  @override
  _i4.Future<_i2.UserCredential> signIn({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i4.Future<_i2.UserCredential>.value(
              _FakeUserCredential_0(
                this,
                Invocation.method(#signIn, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.UserCredential>);

  @override
  _i4.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> resetPassword(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [email]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateEmail(String? newEmail) =>
      (super.noSuchMethod(
            Invocation.method(#updateEmail, [newEmail]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updatePassword(String? newPassword) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [newPassword]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> reauthenticate(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticate, [email, password]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [FirestoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreService extends _i1.Mock implements _i8.FirestoreService {
  MockFirestoreService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.FirebaseFirestore get instance =>
      (super.noSuchMethod(
            Invocation.getter(#instance),
            returnValue: _FakeFirebaseFirestore_1(
              this,
              Invocation.getter(#instance),
            ),
          )
          as _i3.FirebaseFirestore);

  @override
  _i3.CollectionReference<Object?> get users =>
      (super.noSuchMethod(
            Invocation.getter(#users),
            returnValue: _FakeCollectionReference_2<Object?>(
              this,
              Invocation.getter(#users),
            ),
          )
          as _i3.CollectionReference<Object?>);

  @override
  _i3.CollectionReference<Object?> get posts =>
      (super.noSuchMethod(
            Invocation.getter(#posts),
            returnValue: _FakeCollectionReference_2<Object?>(
              this,
              Invocation.getter(#posts),
            ),
          )
          as _i3.CollectionReference<Object?>);

  @override
  _i3.CollectionReference<Object?> get restaurants =>
      (super.noSuchMethod(
            Invocation.getter(#restaurants),
            returnValue: _FakeCollectionReference_2<Object?>(
              this,
              Invocation.getter(#restaurants),
            ),
          )
          as _i3.CollectionReference<Object?>);

  @override
  _i3.CollectionReference<Object?> get follows =>
      (super.noSuchMethod(
            Invocation.getter(#follows),
            returnValue: _FakeCollectionReference_2<Object?>(
              this,
              Invocation.getter(#follows),
            ),
          )
          as _i3.CollectionReference<Object?>);

  @override
  _i3.CollectionReference<Object?> get savedPosts =>
      (super.noSuchMethod(
            Invocation.getter(#savedPosts),
            returnValue: _FakeCollectionReference_2<Object?>(
              this,
              Invocation.getter(#savedPosts),
            ),
          )
          as _i3.CollectionReference<Object?>);

  @override
  _i3.FieldValue get serverTimestamp =>
      (super.noSuchMethod(
            Invocation.getter(#serverTimestamp),
            returnValue: _FakeFieldValue_3(
              this,
              Invocation.getter(#serverTimestamp),
            ),
          )
          as _i3.FieldValue);

  @override
  _i4.Future<void> enableOfflinePersistence() =>
      (super.noSuchMethod(
            Invocation.method(#enableOfflinePersistence, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i3.WriteBatch batch() =>
      (super.noSuchMethod(
            Invocation.method(#batch, []),
            returnValue: _FakeWriteBatch_4(this, Invocation.method(#batch, [])),
          )
          as _i3.WriteBatch);

  @override
  _i4.Future<T> runTransaction<T>(
    _i3.TransactionHandler<T>? transactionHandler,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#runTransaction, [transactionHandler]),
            returnValue:
                _i9.ifNotNull(
                  _i9.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#runTransaction, [transactionHandler]),
                  ),
                  (T v) => _i4.Future<T>.value(v),
                ) ??
                _FakeFuture_5<T>(
                  this,
                  Invocation.method(#runTransaction, [transactionHandler]),
                ),
          )
          as _i4.Future<T>);

  @override
  _i3.FieldValue increment(num? value) =>
      (super.noSuchMethod(
            Invocation.method(#increment, [value]),
            returnValue: _FakeFieldValue_3(
              this,
              Invocation.method(#increment, [value]),
            ),
          )
          as _i3.FieldValue);

  @override
  _i3.FieldValue arrayUnion(List<dynamic>? elements) =>
      (super.noSuchMethod(
            Invocation.method(#arrayUnion, [elements]),
            returnValue: _FakeFieldValue_3(
              this,
              Invocation.method(#arrayUnion, [elements]),
            ),
          )
          as _i3.FieldValue);

  @override
  _i3.FieldValue arrayRemove(List<dynamic>? elements) =>
      (super.noSuchMethod(
            Invocation.method(#arrayRemove, [elements]),
            returnValue: _FakeFieldValue_3(
              this,
              Invocation.method(#arrayRemove, [elements]),
            ),
          )
          as _i3.FieldValue);
}

/// A class which mocks [BackendService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackendService extends _i1.Mock implements _i5.BackendService {
  MockBackendService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> isBackendAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isBackendAvailable, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i5.ImageUploadResult> uploadImage(_i10.File? imageFile) =>
      (super.noSuchMethod(
            Invocation.method(#uploadImage, [imageFile]),
            returnValue: _i4.Future<_i5.ImageUploadResult>.value(
              _FakeImageUploadResult_6(
                this,
                Invocation.method(#uploadImage, [imageFile]),
              ),
            ),
          )
          as _i4.Future<_i5.ImageUploadResult>);

  @override
  _i4.Future<_i5.MultiImageUploadResult> uploadMultipleImages(
    List<_i10.File>? imageFiles,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadMultipleImages, [imageFiles]),
            returnValue: _i4.Future<_i5.MultiImageUploadResult>.value(
              _FakeMultiImageUploadResult_7(
                this,
                Invocation.method(#uploadMultipleImages, [imageFiles]),
              ),
            ),
          )
          as _i4.Future<_i5.MultiImageUploadResult>);

  @override
  _i4.Future<bool> deleteImage(String? publicId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteImage, [publicId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i5.ModerationResult> checkText(String? text) =>
      (super.noSuchMethod(
            Invocation.method(#checkText, [text]),
            returnValue: _i4.Future<_i5.ModerationResult>.value(
              _FakeModerationResult_8(
                this,
                Invocation.method(#checkText, [text]),
              ),
            ),
          )
          as _i4.Future<_i5.ModerationResult>);

  @override
  _i4.Future<_i5.ValidationResult> validatePost(
    String? caption, {
    String? restaurantId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #validatePost,
              [caption],
              {#restaurantId: restaurantId},
            ),
            returnValue: _i4.Future<_i5.ValidationResult>.value(
              _FakeValidationResult_9(
                this,
                Invocation.method(
                  #validatePost,
                  [caption],
                  {#restaurantId: restaurantId},
                ),
              ),
            ),
          )
          as _i4.Future<_i5.ValidationResult>);

  @override
  _i4.Future<_i5.ValidationResult> validateComment(String? text) =>
      (super.noSuchMethod(
            Invocation.method(#validateComment, [text]),
            returnValue: _i4.Future<_i5.ValidationResult>.value(
              _FakeValidationResult_9(
                this,
                Invocation.method(#validateComment, [text]),
              ),
            ),
          )
          as _i4.Future<_i5.ValidationResult>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getTrending({
    String? type = 'posts',
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTrending, [], {#type: type, #limit: limit}),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getLeaderboard({int? limit = 20}) =>
      (super.noSuchMethod(
            Invocation.method(#getLeaderboard, [], {#limit: limit}),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<_i5.UserSummary?> getUserSummary(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getUserSummary, [uid]),
            returnValue: _i4.Future<_i5.UserSummary?>.value(),
          )
          as _i4.Future<_i5.UserSummary?>);
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i11.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> initialize({
    required dynamic Function(Map<String, dynamic>)? onNotificationTap,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [], {
              #onNotificationTap: onNotificationTap,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i12.AppNotification>> getNotifications({
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getNotifications, [], {
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i4.Future<List<_i12.AppNotification>>.value(
              <_i12.AppNotification>[],
            ),
          )
          as _i4.Future<List<_i12.AppNotification>>);

  @override
  _i4.Future<int> getUnreadCount() =>
      (super.noSuchMethod(
            Invocation.method(#getUnreadCount, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> markAsRead(String? notificationId) =>
      (super.noSuchMethod(
            Invocation.method(#markAsRead, [notificationId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> markAllAsRead() =>
      (super.noSuchMethod(
            Invocation.method(#markAllAsRead, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteNotification(String? notificationId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNotification, [notificationId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteAllNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllNotifications, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> sendTestNotification() =>
      (super.noSuchMethod(
            Invocation.method(#sendTestNotification, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i13.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  _i4.Stream<_i2.User?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i4.Stream<_i2.User?>.empty(),
          )
          as _i4.Stream<_i2.User?>);

  @override
  _i4.Stream<_i6.User?> get currentUserStream =>
      (super.noSuchMethod(
            Invocation.getter(#currentUserStream),
            returnValue: _i4.Stream<_i6.User?>.empty(),
          )
          as _i4.Stream<_i6.User?>);

  @override
  _i4.Future<_i6.User> signUp({
    required String? username,
    required String? email,
    required String? password,
    String? displayName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #username: username,
              #email: email,
              #password: password,
              #displayName: displayName,
            }),
            returnValue: _i4.Future<_i6.User>.value(
              _FakeUser_10(
                this,
                Invocation.method(#signUp, [], {
                  #username: username,
                  #email: email,
                  #password: password,
                  #displayName: displayName,
                }),
              ),
            ),
          )
          as _i4.Future<_i6.User>);

  @override
  _i4.Future<_i6.User> signIn({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i4.Future<_i6.User>.value(
              _FakeUser_10(
                this,
                Invocation.method(#signIn, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i4.Future<_i6.User>);

  @override
  _i4.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i6.User?> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i4.Future<_i6.User?>.value(),
          )
          as _i4.Future<_i6.User?>);

  @override
  _i4.Future<_i6.User?> getUserByUid(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByUid, [uid]),
            returnValue: _i4.Future<_i6.User?>.value(),
          )
          as _i4.Future<_i6.User?>);

  @override
  _i4.Future<_i6.User?> getUserByEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByEmail, [email]),
            returnValue: _i4.Future<_i6.User?>.value(),
          )
          as _i4.Future<_i6.User?>);

  @override
  _i4.Future<bool> usernameExists(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#usernameExists, [username]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> updateUserProfile(_i6.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfile, [user]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> sendPasswordResetEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [email]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateEmail(String? newEmail) =>
      (super.noSuchMethod(
            Invocation.method(#updateEmail, [newEmail]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updatePassword(String? newPassword) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [newPassword]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> reauthenticate(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticate, [email, password]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<_i6.User?> getUserStream(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getUserStream, [uid]),
            returnValue: _i4.Stream<_i6.User?>.empty(),
          )
          as _i4.Stream<_i6.User?>);
}

/// A class which mocks [PostRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostRepository extends _i1.Mock implements _i14.PostRepository {
  MockPostRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> createPost({
    required String? userUid,
    required String? username,
    required String? userAvatarUrl,
    required String? caption,
    required List<_i10.File>? imageFiles,
    String? restaurantUid,
    String? restaurantName,
    String? dishName,
    double? rating,
    String? explicitChallengeId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPost, [], {
              #userUid: userUid,
              #username: username,
              #userAvatarUrl: userAvatarUrl,
              #caption: caption,
              #imageFiles: imageFiles,
              #restaurantUid: restaurantUid,
              #restaurantName: restaurantName,
              #dishName: dishName,
              #rating: rating,
              #explicitChallengeId: explicitChallengeId,
            }),
            returnValue: _i4.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#createPost, [], {
                  #userUid: userUid,
                  #username: username,
                  #userAvatarUrl: userAvatarUrl,
                  #caption: caption,
                  #imageFiles: imageFiles,
                  #restaurantUid: restaurantUid,
                  #restaurantName: restaurantName,
                  #dishName: dishName,
                  #rating: rating,
                  #explicitChallengeId: explicitChallengeId,
                }),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<_i15.Post?> getPostById(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#getPostById, [postId]),
            returnValue: _i4.Future<_i15.Post?>.value(),
          )
          as _i4.Future<_i15.Post?>);

  @override
  _i4.Future<List<_i15.Post>> getUserPosts(
    String? userUid, {
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUserPosts, [userUid], {#limit: limit}),
            returnValue: _i4.Future<List<_i15.Post>>.value(<_i15.Post>[]),
          )
          as _i4.Future<List<_i15.Post>>);

  @override
  _i4.Future<List<_i15.Post>> getRestaurantPosts(
    String? restaurantUid, {
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getRestaurantPosts,
              [restaurantUid],
              {#limit: limit},
            ),
            returnValue: _i4.Future<List<_i15.Post>>.value(<_i15.Post>[]),
          )
          as _i4.Future<List<_i15.Post>>);

  @override
  _i4.Future<List<_i15.Post>> getFeedPosts({
    int? limit = 20,
    _i3.DocumentSnapshot<Object?>? lastDocument,
    List<String>? userIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFeedPosts, [], {
              #limit: limit,
              #lastDocument: lastDocument,
              #userIds: userIds,
            }),
            returnValue: _i4.Future<List<_i15.Post>>.value(<_i15.Post>[]),
          )
          as _i4.Future<List<_i15.Post>>);

  @override
  _i4.Future<List<_i15.Post>> searchPosts(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchPosts, [query]),
            returnValue: _i4.Future<List<_i15.Post>>.value(<_i15.Post>[]),
          )
          as _i4.Future<List<_i15.Post>>);

  @override
  _i4.Future<int> getUserPostsCount(String? userUid) =>
      (super.noSuchMethod(
            Invocation.method(#getUserPostsCount, [userUid]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> getRestaurantPostsCount(String? restaurantUid) =>
      (super.noSuchMethod(
            Invocation.method(#getRestaurantPostsCount, [restaurantUid]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Stream<List<_i15.Post>> getPostsStream({int? limit = 20}) =>
      (super.noSuchMethod(
            Invocation.method(#getPostsStream, [], {#limit: limit}),
            returnValue: _i4.Stream<List<_i15.Post>>.empty(),
          )
          as _i4.Stream<List<_i15.Post>>);

  @override
  _i4.Stream<List<_i15.Post>> getUserPostsStream(
    String? userUid, {
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUserPostsStream, [userUid], {#limit: limit}),
            returnValue: _i4.Stream<List<_i15.Post>>.empty(),
          )
          as _i4.Stream<List<_i15.Post>>);

  @override
  _i4.Future<void> updatePost(_i15.Post? post) =>
      (super.noSuchMethod(
            Invocation.method(#updatePost, [post]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updatePostUserByUid({
    required String? userUid,
    required String? username,
    required String? userAvatarUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePostUserByUid, [], {
              #userUid: userUid,
              #username: username,
              #userAvatarUrl: userAvatarUrl,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> incrementLikesCount(String? postId, String? userUid) =>
      (super.noSuchMethod(
            Invocation.method(#incrementLikesCount, [postId, userUid]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> decrementLikesCount(String? postId, String? userUid) =>
      (super.noSuchMethod(
            Invocation.method(#decrementLikesCount, [postId, userUid]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> incrementCommentsCount(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#incrementCommentsCount, [postId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> decrementCommentsCount(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#decrementCommentsCount, [postId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> addToSavedBy(String? postId, String? userUid) =>
      (super.noSuchMethod(
            Invocation.method(#addToSavedBy, [postId, userUid]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeFromSavedBy(String? postId, String? userUid) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromSavedBy, [postId, userUid]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deletePost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePost, [postId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteUserPosts(String? userUid) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUserPosts, [userUid]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> postExists(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#postExists, [postId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<int> getTotalPostsCount() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalPostsCount, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<bool> isPostLikedByUser(String? postId, String? userUid) =>
      (super.noSuchMethod(
            Invocation.method(#isPostLikedByUser, [postId, userUid]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> isPostSavedByUser(String? postId, String? userUid) =>
      (super.noSuchMethod(
            Invocation.method(#isPostSavedByUser, [postId, userUid]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<List<_i15.Post>> getPostsByUserId(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getPostsByUserId, [userId]),
            returnValue: _i4.Future<List<_i15.Post>>.value(<_i15.Post>[]),
          )
          as _i4.Future<List<_i15.Post>>);

  @override
  _i4.Future<List<_i15.Post>> getAllPosts() =>
      (super.noSuchMethod(
            Invocation.method(#getAllPosts, []),
            returnValue: _i4.Future<List<_i15.Post>>.value(<_i15.Post>[]),
          )
          as _i4.Future<List<_i15.Post>>);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i16.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i6.User?> getUserByUid(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByUid, [uid]),
            returnValue: _i4.Future<_i6.User?>.value(),
          )
          as _i4.Future<_i6.User?>);

  @override
  _i4.Future<_i6.User?> getUserByEmailFirestore(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByEmailFirestore, [email]),
            returnValue: _i4.Future<_i6.User?>.value(),
          )
          as _i4.Future<_i6.User?>);

  @override
  _i4.Future<void> updateUserFirestore(_i6.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserFirestore, [user]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setUserFirestore(_i6.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#setUserFirestore, [user]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteUserFirestore(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUserFirestore, [uid]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.User>> getAllUsersFirestore() =>
      (super.noSuchMethod(
            Invocation.method(#getAllUsersFirestore, []),
            returnValue: _i4.Future<List<_i6.User>>.value(<_i6.User>[]),
          )
          as _i4.Future<List<_i6.User>>);

  @override
  _i4.Future<List<_i6.User>> searchUsersFirestore(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchUsersFirestore, [query]),
            returnValue: _i4.Future<List<_i6.User>>.value(<_i6.User>[]),
          )
          as _i4.Future<List<_i6.User>>);

  @override
  _i4.Stream<_i6.User?> getUserStreamFirestore(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getUserStreamFirestore, [uid]),
            returnValue: _i4.Stream<_i6.User?>.empty(),
          )
          as _i4.Stream<_i6.User?>);
}

/// A class which mocks [RestaurantRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRestaurantRepository extends _i1.Mock
    implements _i17.RestaurantRepository {
  MockRestaurantRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> createRestaurant(_i18.Restaurant? restaurant) =>
      (super.noSuchMethod(
            Invocation.method(#createRestaurant, [restaurant]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String> addDish(_i19.Dish? dish) =>
      (super.noSuchMethod(
            Invocation.method(#addDish, [dish]),
            returnValue: _i4.Future<String>.value(
              _i9.dummyValue<String>(this, Invocation.method(#addDish, [dish])),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<_i18.Restaurant?> getRestaurantById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getRestaurantById, [id]),
            returnValue: _i4.Future<_i18.Restaurant?>.value(),
          )
          as _i4.Future<_i18.Restaurant?>);

  @override
  _i4.Future<List<_i19.Dish>> getDishesForRestaurant(String? restaurantId) =>
      (super.noSuchMethod(
            Invocation.method(#getDishesForRestaurant, [restaurantId]),
            returnValue: _i4.Future<List<_i19.Dish>>.value(<_i19.Dish>[]),
          )
          as _i4.Future<List<_i19.Dish>>);

  @override
  _i4.Future<List<_i18.Restaurant>> getAllRestaurants({int? limit = 50}) =>
      (super.noSuchMethod(
            Invocation.method(#getAllRestaurants, [], {#limit: limit}),
            returnValue: _i4.Future<List<_i18.Restaurant>>.value(
              <_i18.Restaurant>[],
            ),
          )
          as _i4.Future<List<_i18.Restaurant>>);

  @override
  _i4.Future<List<_i18.Restaurant>> searchRestaurants(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchRestaurants, [query]),
            returnValue: _i4.Future<List<_i18.Restaurant>>.value(
              <_i18.Restaurant>[],
            ),
          )
          as _i4.Future<List<_i18.Restaurant>>);

  @override
  _i4.Future<List<_i18.Restaurant>> getTopRatedRestaurants({int? limit = 10}) =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedRestaurants, [], {#limit: limit}),
            returnValue: _i4.Future<List<_i18.Restaurant>>.value(
              <_i18.Restaurant>[],
            ),
          )
          as _i4.Future<List<_i18.Restaurant>>);

  @override
  _i4.Future<_i18.Restaurant?> getRestaurantByName(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#getRestaurantByName, [name]),
            returnValue: _i4.Future<_i18.Restaurant?>.value(),
          )
          as _i4.Future<_i18.Restaurant?>);

  @override
  _i4.Future<List<_i18.Restaurant>> getTrendingRestaurants({int? limit = 10}) =>
      (super.noSuchMethod(
            Invocation.method(#getTrendingRestaurants, [], {#limit: limit}),
            returnValue: _i4.Future<List<_i18.Restaurant>>.value(
              <_i18.Restaurant>[],
            ),
          )
          as _i4.Future<List<_i18.Restaurant>>);

  @override
  _i4.Future<void> updateRating(String? restaurantId, double? newRating) =>
      (super.noSuchMethod(
            Invocation.method(#updateRating, [restaurantId, newRating]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> recalculateAverageRating(String? restaurantId) =>
      (super.noSuchMethod(
            Invocation.method(#recalculateAverageRating, [restaurantId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateRestaurant(_i18.Restaurant? restaurant) =>
      (super.noSuchMethod(
            Invocation.method(#updateRestaurant, [restaurant]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateDish(_i19.Dish? dish) =>
      (super.noSuchMethod(
            Invocation.method(#updateDish, [dish]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteDish(String? restaurantId, String? dishId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDish, [restaurantId, dishId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> incrementPostsCount(String? restaurantId) =>
      (super.noSuchMethod(
            Invocation.method(#incrementPostsCount, [restaurantId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> decrementPostsCount(String? restaurantId) =>
      (super.noSuchMethod(
            Invocation.method(#decrementPostsCount, [restaurantId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteRestaurant(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRestaurant, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [ReviewRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockReviewRepository extends _i1.Mock implements _i20.ReviewRepository {
  MockReviewRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> addReview(_i21.Review? review) =>
      (super.noSuchMethod(
            Invocation.method(#addReview, [review]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i21.Review>> getReviewsForRestaurant(String? restaurantId) =>
      (super.noSuchMethod(
            Invocation.method(#getReviewsForRestaurant, [restaurantId]),
            returnValue: _i4.Future<List<_i21.Review>>.value(<_i21.Review>[]),
          )
          as _i4.Future<List<_i21.Review>>);
}

/// A class which mocks [FollowRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFollowRepository extends _i1.Mock implements _i22.FollowRepository {
  MockFollowRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> followUser({
    required String? currentUserId,
    required String? targetUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#followUser, [], {
              #currentUserId: currentUserId,
              #targetUserId: targetUserId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> unfollowUser({
    required String? currentUserId,
    required String? targetUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#unfollowUser, [], {
              #currentUserId: currentUserId,
              #targetUserId: targetUserId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> isFollowing(String? currentUserId, String? targetUserId) =>
      (super.noSuchMethod(
            Invocation.method(#isFollowing, [currentUserId, targetUserId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<List<String>> getFollowingIds(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getFollowingIds, [userId]),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Future<List<String>> getFollowerIds(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getFollowerIds, [userId]),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);
}
